---
deployment:
  tasks:
    - export DEPLOYPATH=/home/i0gblxg6zh32/public_html/HVAC_Website/
    - export DEPLOYPATH1=/home/i0gblxg6zh32/public_html/HVAC_Website/css/
    - export DEPLOYPATH2=/home/i0gblxg6zh32/public_html/HVAC_Website/fonts/
    - export DEPLOYPATH3=/home/i0gblxg6zh32/public_html/HVAC_Website/img/
    - export DEPLOYPATH4=/home/i0gblxg6zh32/public_html/HVAC_Website/js/
    - export DEPLOYPATH5=/home/i0gblxg6zh32/public_html/HVAC_Website/sass/

    - /bin/cp * $DEPLOYPATH
    - /bin/cp/ * $DEPLOYPATH1
    - /bin/cp/ * $DEPLOYPATH2
    - /bin/cp/ * $DEPLOYPATH3
    - /bin/cp/ * $DEPLOYPATH4
    - /bin/cp/ * $DEPLOYPATH5
